// Code generated by scripts/generate_services.py; DO NOT EDIT.

package audit

// Endpoint identifies a audit service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "GET", Path: "/audit/events"},
	{Method: "POST", Path: "/audit/events"},
	{Method: "POST", Path: "/audit/events/batch"},
	{Method: "GET", Path: "/audit/events/{param}"},
}
