// Code generated by scripts/generate_services.py; DO NOT EDIT.

package sandbox

// Endpoint identifies a sandbox service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "GET", Path: "/sandbox/languages"},
	{Method: "POST", Path: "/sandbox/self-test"},
	{Method: "POST", Path: "/sandbox/submit"},
}
