// Code generated by scripts/generate_services.py; DO NOT EDIT.

package functions

// Endpoint identifies a functions service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "GET", Path: "/functions"},
	{Method: "POST", Path: "/functions"},
	{Method: "GET", Path: "/functions/executions"},
	{Method: "GET", Path: "/functions/executions/{param}"},
	{Method: "POST", Path: "/functions/executions/{param}/cancel"},
	{Method: "GET", Path: "/functions/executions/{param}/result"},
	{Method: "POST", Path: "/functions/invoke"},
	{Method: "POST", Path: "/functions/invoke-async"},
	{Method: "DELETE", Path: "/functions/{param}"},
	{Method: "GET", Path: "/functions/{param}"},
	{Method: "PATCH", Path: "/functions/{param}"},
	{Method: "GET", Path: "/functions/{param}/versions"},
	{Method: "GET", Path: "/functions/{param}/versions/{param}"},
	{Method: "POST", Path: "/functions/{param}/versions/{param}/deploy"},
	{Method: "GET", Path: "/functions/{param}/versions/{param}/deployment/status"},
	{Method: "POST", Path: "/functions/{param}/versions/{param}/publish"},
}
