version: "2"
run:
  timeout: 5m
linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
  exclusions:
    generated: strict
formatters:
  enable:
    - gofumpt
    - goimports
