version: 2
project_name: sdk-go
builds:
  - skip: true
release:
  github:
    owner: frontal-labs
    name: sdk-go
  extra_files:
    - glob: dist/sdk-go-*-source.tar.gz
    - glob: dist/sbom.spdx.json
changelog:
  use: github-native
