// Code generated by scripts/generate_services.py; DO NOT EDIT.

package lineage

// Endpoint identifies a lineage service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "GET", Path: "/lineage/edges"},
	{Method: "GET", Path: "/lineage/edges/{param}"},
	{Method: "GET", Path: "/lineage/graph"},
	{Method: "POST", Path: "/lineage/impact"},
	{Method: "GET", Path: "/lineage/nodes"},
	{Method: "GET", Path: "/lineage/nodes/{param}"},
	{Method: "GET", Path: "/lineage/nodes/{param}/trace"},
}
