// Code generated by scripts/generate_services.py; DO NOT EDIT.

// Package schedules provides the schedules service client.
package schedules

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
)

// Request describes an operation in the schedules endpoint inventory.
type Request struct {
	Endpoint   Endpoint
	PathParams []string
	Query      url.Values
	Headers    http.Header
	Body       any
}

// CallFunc sends a JSON operation through the parent Frontal client.
type CallFunc func(context.Context, string, string, []string, url.Values, http.Header, any, any) error

// StreamFunc opens a streaming operation through the parent Frontal client.
type StreamFunc func(context.Context, string, string, []string, url.Values, http.Header, any) (*http.Response, error)

// Client calls operations in the schedules service.
type Client struct {
	call   CallFunc
	stream StreamFunc
}

// NewClient creates a service client attached to a parent Frontal client.
func NewClient(call CallFunc, stream StreamFunc) *Client {
	return &Client{call: call, stream: stream}
}

// Endpoints returns a copy of the service's endpoint inventory.
func (client *Client) Endpoints() []Endpoint {
	return append([]Endpoint(nil), generatedEndpoints[:]...)
}

// Endpoint finds a method/path operation in the service inventory.
func (client *Client) Endpoint(method, path string) (Endpoint, bool) {
	for _, endpoint := range generatedEndpoints {
		if endpoint.Method == method && endpoint.Path == path {
			return endpoint, true
		}
	}
	return Endpoint{}, false
}

// Call sends a contract-backed operation. Use generated operation methods when
// available; Request keeps unsupported operations accessible without guessing schemas.
func (client *Client) Call(ctx context.Context, request Request, out any) error {
	if client == nil || client.call == nil {
		return errors.New("frontal: schedules client is not configured")
	}
	endpoint, ok := client.Endpoint(request.Endpoint.Method, request.Endpoint.Path)
	if !ok {
		return fmt.Errorf("frontal: schedules endpoint is not in this service's contract: %s %s", request.Endpoint.Method, request.Endpoint.Path)
	}
	return client.call(ctx, endpoint.Method, endpoint.Path, request.PathParams, request.Query, request.Headers, request.Body, out)
}

// Stream opens a stream for an operation in this service. The caller owns the response body.
func (client *Client) Stream(ctx context.Context, request Request) (*http.Response, error) {
	if client == nil || client.stream == nil {
		return nil, errors.New("frontal: schedules stream client is not configured")
	}
	endpoint, ok := client.Endpoint(request.Endpoint.Method, request.Endpoint.Path)
	if !ok {
		return nil, fmt.Errorf("frontal: schedules endpoint is not in this service's contract: %s %s", request.Endpoint.Method, request.Endpoint.Path)
	}
	return client.stream(ctx, endpoint.Method, endpoint.Path, request.PathParams, request.Query, request.Headers, request.Body)
}
