// Code generated by scripts/generate_services.py; DO NOT EDIT.

package schedules

// Endpoint identifies a schedules service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "POST", Path: "/workflows/cron/parse"},
	{Method: "POST", Path: "/workflows/cron/validate"},
	{Method: "GET", Path: "/workflows/schedules"},
	{Method: "POST", Path: "/workflows/schedules"},
	{Method: "DELETE", Path: "/workflows/schedules/{param}"},
	{Method: "GET", Path: "/workflows/schedules/{param}"},
	{Method: "PATCH", Path: "/workflows/schedules/{param}"},
	{Method: "POST", Path: "/workflows/schedules/{param}/pause"},
	{Method: "POST", Path: "/workflows/schedules/{param}/resume"},
	{Method: "POST", Path: "/workflows/schedules/{param}/trigger"},
}
