// Code generated by scripts/generate_services.py; DO NOT EDIT.

package governance

// Endpoint identifies a governance service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "POST", Path: "/access/check"},
	{Method: "GET", Path: "/compliance/assessments"},
	{Method: "POST", Path: "/compliance/assessments"},
	{Method: "GET", Path: "/compliance/assessments/{param}"},
	{Method: "GET", Path: "/compliance/frameworks"},
	{Method: "GET", Path: "/compliance/score"},
	{Method: "GET", Path: "/compliance/violations"},
	{Method: "POST", Path: "/compliance/violations/{param}/resolve"},
	{Method: "GET", Path: "/permissions"},
	{Method: "POST", Path: "/permissions"},
	{Method: "GET", Path: "/permissions/{param}"},
	{Method: "GET", Path: "/policies"},
	{Method: "POST", Path: "/policies"},
	{Method: "POST", Path: "/policies/from-template"},
	{Method: "GET", Path: "/policies/templates"},
	{Method: "POST", Path: "/policies/validate"},
	{Method: "DELETE", Path: "/policies/{param}"},
	{Method: "GET", Path: "/policies/{param}"},
	{Method: "PUT", Path: "/policies/{param}"},
	{Method: "GET", Path: "/policies/{param}/versions"},
	{Method: "GET", Path: "/roles"},
	{Method: "POST", Path: "/roles"},
	{Method: "DELETE", Path: "/roles/{param}"},
	{Method: "GET", Path: "/roles/{param}"},
}
