// Code generated by scripts/generate_services.py; DO NOT EDIT.

package observability

// Endpoint identifies a observability service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "GET", Path: "/events"},
	{Method: "POST", Path: "/events"},
	{Method: "POST", Path: "/events/analytics"},
	{Method: "POST", Path: "/events/analytics-v2"},
	{Method: "POST", Path: "/events/benchmark/v1"},
	{Method: "POST", Path: "/events/benchmark/v2"},
	{Method: "POST", Path: "/events/bulk"},
	{Method: "POST", Path: "/events/huggingface-billing"},
	{Method: "GET", Path: "/events/monitoring"},
	{Method: "POST", Path: "/events/query"},
	{Method: "POST", Path: "/events/raw/reprocess/all"},
	{Method: "POST", Path: "/events/raw/reprocess/pending"},
	{Method: "POST", Path: "/events/reprocess"},
	{Method: "POST", Path: "/events/reprocess/internal"},
	{Method: "POST", Path: "/events/usage"},
	{Method: "POST", Path: "/events/usage/meter"},
	{Method: "GET", Path: "/events/{param}"},
	{Method: "GET", Path: "/observability/alerts"},
	{Method: "POST", Path: "/observability/alerts"},
	{Method: "GET", Path: "/observability/alerts/incidents"},
	{Method: "GET", Path: "/observability/alerts/rules"},
	{Method: "POST", Path: "/observability/alerts/rules"},
	{Method: "DELETE", Path: "/observability/alerts/rules/{param}"},
	{Method: "GET", Path: "/observability/alerts/rules/{param}"},
	{Method: "PUT", Path: "/observability/alerts/rules/{param}"},
	{Method: "POST", Path: "/observability/alerts/rules/{param}/toggle"},
	{Method: "DELETE", Path: "/observability/alerts/{param}"},
	{Method: "PUT", Path: "/observability/alerts/{param}"},
	{Method: "POST", Path: "/observability/alerts/{param}/disable"},
	{Method: "POST", Path: "/observability/alerts/{param}/enable"},
	{Method: "GET", Path: "/observability/dashboards"},
	{Method: "POST", Path: "/observability/dashboards"},
	{Method: "DELETE", Path: "/observability/dashboards/{param}"},
	{Method: "GET", Path: "/observability/dashboards/{param}"},
	{Method: "PUT", Path: "/observability/dashboards/{param}"},
	{Method: "POST", Path: "/observability/dashboards/{param}/share"},
	{Method: "POST", Path: "/observability/events"},
	{Method: "POST", Path: "/observability/events/batch"},
	{Method: "GET", Path: "/observability/events/stats"},
	{Method: "POST", Path: "/observability/logs/ingest"},
	{Method: "POST", Path: "/observability/logs/query"},
	{Method: "STREAM", Path: "/observability/logs/stream"},
	{Method: "GET", Path: "/observability/metrics"},
	{Method: "POST", Path: "/observability/metrics/ingest"},
	{Method: "GET", Path: "/observability/metrics/list"},
	{Method: "GET", Path: "/observability/traces"},
	{Method: "POST", Path: "/observability/traces/query"},
	{Method: "GET", Path: "/observability/traces/{param}"},
}
