// Code generated by scripts/generate_services.py; DO NOT EDIT.

package billing

// Endpoint identifies a billing service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "GET", Path: "/billing/addons/{param}/entitlements"},
	{Method: "GET", Path: "/billing/customers/portal/{param}"},
	{Method: "GET", Path: "/billing/customers/{param}/entitlements"},
	{Method: "GET", Path: "/billing/customers/{param}/invoices/summary"},
	{Method: "GET", Path: "/billing/customers/{param}/usage"},
	{Method: "GET", Path: "/billing/customers/{param}/wallets"},
	{Method: "POST", Path: "/billing/invoices/preview"},
	{Method: "POST", Path: "/billing/invoices/{param}/finalize"},
	{Method: "GETRAW", Path: "/billing/invoices/{param}/pdf"},
	{Method: "POST", Path: "/billing/invoices/{param}/void"},
	{Method: "POST", Path: "/billing/meters/{param}/disable"},
	{Method: "POST", Path: "/billing/plans/{param}/clone"},
	{Method: "GET", Path: "/billing/plans/{param}/entitlements"},
	{Method: "GET", Path: "/billing/prices/lookup/{param}"},
	{Method: "POST", Path: "/billing/subscriptions/{param}/activate"},
	{Method: "POST", Path: "/billing/subscriptions/{param}/cancel"},
	{Method: "GET", Path: "/billing/subscriptions/{param}/entitlements"},
	{Method: "POST", Path: "/billing/subscriptions/{param}/pause"},
	{Method: "POST", Path: "/billing/subscriptions/{param}/resume"},
	{Method: "GET", Path: "/billing/wallets/{param}/balance/real-time"},
	{Method: "POST", Path: "/billing/wallets/{param}/terminate"},
	{Method: "POST", Path: "/billing/wallets/{param}/top-up"},
	{Method: "GET", Path: "/billing/wallets/{param}/transactions"},
}
