// Code generated by scripts/generate_services.py; DO NOT EDIT.

package pipelines

// Endpoint identifies a pipelines service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "GET", Path: "/data/pipelines/capabilities"},
	{Method: "GET", Path: "/data/pipelines/health"},
	{Method: "GET", Path: "/data/pipelines/info"},
	{Method: "GET", Path: "/data/pipelines/pipeline-runs"},
	{Method: "GET", Path: "/data/pipelines/pipeline-runs/{param}"},
	{Method: "STREAM", Path: "/data/pipelines/pipeline-runs/{param}"},
	{Method: "GET", Path: "/data/pipelines/pipelines"},
	{Method: "POST", Path: "/data/pipelines/pipelines"},
	{Method: "GET", Path: "/data/pipelines/pipelines/{param}"},
	{Method: "GET", Path: "/data/pipelines/runs"},
	{Method: "POST", Path: "/data/pipelines/runs"},
}
