// Code generated by scripts/generate_services.py; DO NOT EDIT.

package workflows

// Endpoint identifies a workflows service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "GET", Path: "/workflows"},
	{Method: "POST", Path: "/workflows"},
	{Method: "GET", Path: "/workflows/approvals"},
	{Method: "GET", Path: "/workflows/approvals/{param}"},
	{Method: "POST", Path: "/workflows/approvals/{param}/approve"},
	{Method: "POST", Path: "/workflows/approvals/{param}/reject"},
	{Method: "POST", Path: "/workflows/batch"},
	{Method: "GET", Path: "/workflows/executions"},
	{Method: "POST", Path: "/workflows/executions"},
	{Method: "GET", Path: "/workflows/executions/{param}"},
	{Method: "GET", Path: "/workflows/executions/{param}/tasks"},
	{Method: "GET", Path: "/workflows/runs/{param}/steps"},
	{Method: "POST", Path: "/workflows/search"},
	{Method: "GET", Path: "/workflows/tasks/{param}"},
	{Method: "POST", Path: "/workflows/tasks/{param}/cancel"},
	{Method: "POST", Path: "/workflows/tasks/{param}/retry"},
	{Method: "GET", Path: "/workflows/templates"},
	{Method: "POST", Path: "/workflows/templates"},
	{Method: "GET", Path: "/workflows/templates/{param}"},
	{Method: "POST", Path: "/workflows/templates/{param}/instantiate"},
	{Method: "DELETE", Path: "/workflows/{param}"},
	{Method: "GET", Path: "/workflows/{param}"},
	{Method: "PATCH", Path: "/workflows/{param}"},
	{Method: "POST", Path: "/workflows/{param}/archive"},
	{Method: "POST", Path: "/workflows/{param}/publish"},
	{Method: "POST", Path: "/workflows/{param}/restore"},
	{Method: "POST", Path: "/workflows/{param}/versions"},
	{Method: "GET", Path: "/workflows/{param}/{param}"},
	{Method: "GET", Path: "/workflows/{param}/{param}/summary"},
	{Method: "GET", Path: "/workflows/{param}/{param}/timeline"},
}
