// Code generated by scripts/generate_services.py; DO NOT EDIT.

package ai

// Endpoint identifies a ai service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "POST", Path: "/ai/chat/completions"},
	{Method: "GET", Path: "/health"},
	{Method: "POST", Path: "/internal/embeddings"},
	{Method: "GET", Path: "/internal/models"},
	{Method: "GET", Path: "/internal/models/defaults"},
	{Method: "POST", Path: "/internal/predictions"},
	{Method: "POSTFORMDATA", Path: "/internal/predictions"},
	{Method: "POSTRAW", Path: "/internal/predictions"},
	{Method: "POST", Path: "/internal/rerank"},
	{Method: "POST", Path: "/invocations"},
	{Method: "GET", Path: "/providers/{param}"},
}
