// Code generated by scripts/generate_services.py; DO NOT EDIT.

package connectors

// Endpoint identifies a connectors service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "GET", Path: "/action-runs/{param}"},
	{Method: "GET", Path: "/connection-tests/{param}"},
	{Method: "GET", Path: "/connectors/catalog"},
	{Method: "GET", Path: "/connectors/catalog/{param}"},
	{Method: "GET", Path: "/connectors/connection-tests/{param}"},
	{Method: "GET", Path: "/connectors/installations"},
	{Method: "POST", Path: "/connectors/installations"},
	{Method: "DELETE", Path: "/connectors/installations/{param}"},
	{Method: "GET", Path: "/connectors/installations/{param}"},
	{Method: "PATCH", Path: "/connectors/installations/{param}"},
	{Method: "POST", Path: "/connectors/installations/{param}/pause"},
	{Method: "POST", Path: "/connectors/installations/{param}/resume"},
	{Method: "POST", Path: "/connectors/sync-runs/{param}/replay"},
	{Method: "GET", Path: "/diagnostics"},
	{Method: "DELETE", Path: "/integrations/{param}"},
	{Method: "GET", Path: "/integrations/{param}"},
	{Method: "PATCH", Path: "/integrations/{param}"},
	{Method: "GET", Path: "/integrations/{param}/action-runs"},
	{Method: "POST", Path: "/integrations/{param}/action-runs"},
	{Method: "GET", Path: "/integrations/{param}/capabilities"},
	{Method: "PUT", Path: "/integrations/{param}/capabilities/{param}"},
	{Method: "GET", Path: "/integrations/{param}/connection-tests"},
	{Method: "POST", Path: "/integrations/{param}/connection-tests"},
	{Method: "GET", Path: "/integrations/{param}/surfaces"},
	{Method: "PUT", Path: "/integrations/{param}/surfaces/{param}"},
}
