#!/usr/bin/env python3
"""Check committed OpenAPI snapshots and the generated Go endpoint catalog."""

import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "contracts/openapi/manifest.json"
INVENTORY_PATH = ROOT / "contracts/sdk-endpoints.json"
GENERATED_PATH = ROOT / "pkg/resources/endpoints_generated.go"
METHODS = {"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"}
SDK_METHODS = METHODS | {"STREAM", "GETRAW", "POSTRAW", "POSTFORMDATA"}
SERVICE_BY_TAG = {
    "ontology": "ontology",
    "data": "data",
    "events": "observability",
    "observability": "observability",
    "integrations": "connectors",
    "action-runs": "connectors",
    "connection-tests": "connectors",
    "auth": "auth",
    "webhook-endpoints": "webhooks",
    "workflows": "workflows",
    "invocations": "ai",
    "providers": "ai",
    "runtime-api": "ai",
    "gateway": "ai",
    "unified-api": "ai",
}


def load_json(path: Path):
    if not path.is_file():
        fail(f"missing contract file: {path.relative_to(ROOT)}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        fail(f"invalid JSON in {path.relative_to(ROOT)}: {error}")


def fail(message: str):
    raise SystemExit(message)


def normalize_path(path: str) -> str:
    path = path.split("?", 1)[0]
    if path.startswith("/v1/"):
        path = path[3:]
    return re.sub(r"\{[^{}]+\}", "{param}", path)


def wire_method(method: str) -> str:
    return {
        "GETRAW": "GET",
        "STREAM": "GET",
        "POSTRAW": "POST",
        "POSTFORMDATA": "POST",
    }.get(method, method)


def generated_catalog(inventory) -> str:
    entries = []
    for service in sorted(inventory):
        for endpoint in sorted(inventory[service], key=lambda item: (item["path"], item["method"])):
            entries.append(
                "\t{Service: %s, Method: %s, Path: %s},"
                % (
                    json.dumps(service),
                    json.dumps(endpoint["method"]),
                    json.dumps(endpoint["path"]),
                )
            )
    content = "// Code generated by scripts/generate_endpoints.py; DO NOT EDIT.\n\n"
    content += "package resources\n\nvar generatedEndpointCatalog = [...]Endpoint{\n"
    content += "\n".join(entries)
    return content + "\n}\n"


def check_openapi(path: Path, expected_hash: str):
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    if digest != expected_hash:
        fail(
            f"{path.relative_to(ROOT)} differs from openapi/manifest.json; "
            "review the new contract and update the manifest intentionally"
        )

    spec = load_json(path)
    if not isinstance(spec.get("paths"), dict):
        fail(f"{path.relative_to(ROOT)} must contain a paths object")
    operations = {}
    operation_ids = set()
    for path_template, path_item in spec["paths"].items():
        if not path_template.startswith("/") or not isinstance(path_item, dict):
            fail(f"invalid OpenAPI path entry: {path_template!r}")
        for method, operation in path_item.items():
            method = method.upper()
            if method not in METHODS:
                continue
            if not isinstance(operation, dict):
                fail(f"invalid OpenAPI operation: {method} {path_template}")
            operation_id = operation.get("operationId")
            if not isinstance(operation_id, str) or not operation_id:
                fail(f"OpenAPI operation has no operationId: {method} {path_template}")
            if operation_id in operation_ids:
                fail(f"duplicate OpenAPI operationId: {operation_id}")
            operation_ids.add(operation_id)
            tags = operation.get("tags", [])
            if not isinstance(tags, list) or not tags:
                fail(f"OpenAPI operation has no service tag: {method} {path_template}")
            service = SERVICE_BY_TAG.get(tags[0])
            if service is None:
                fail(f"OpenAPI tag {tags[0]!r} has no SDK service mapping: {method} {path_template}")
            operations[(service, method, normalize_path(path_template))] = operation_id
    return operations


def main():
    manifest = load_json(MANIFEST_PATH)
    inventory = load_json(INVENTORY_PATH)
    contracts = manifest.get("contracts", {})

    spec_operations = {}
    for key, filename in (
        ("publicApi", "api.openapi.json"),
        ("aiApi", "ai.openapi.generated.json"),
    ):
        contract = contracts.get(key, {})
        path = ROOT / "contracts/openapi" / filename
        if contract.get("file") != filename or not contract.get("sha256"):
            fail(f"openapi/manifest.json is missing the {key} snapshot hash")
        operations = check_openapi(path, contract["sha256"])
        for operation_key, operation_id in operations.items():
            if operation_key in spec_operations:
                # The AI snapshot intentionally has its own root paths; a collision
                # is only valid when both snapshots identify the same operation.
                if spec_operations[operation_key] != operation_id:
                    fail(f"conflicting OpenAPI operation: {operation_key}")
            spec_operations[operation_key] = operation_id

    endpoint_descriptors = set()
    endpoint_keys = set()
    service_keys = set()
    for service, endpoints in inventory.items():
        if not isinstance(service, str) or not service or not isinstance(endpoints, list):
            fail(f"invalid SDK service inventory entry: {service!r}")
        service_keys.add(service)
        for endpoint in endpoints:
            method = endpoint.get("method")
            path = endpoint.get("path")
            if method not in SDK_METHODS:
                fail(f"unsupported SDK endpoint method: {service} {method}")
            if not isinstance(path, str) or not path.startswith("/") or "#" in path:
                fail(f"invalid SDK endpoint path: {service} {path!r}")
            if "{" in path or "}" in path:
                if re.search(r"\{[^{}]+\}", path) is None or path.count("{") != path.count("}"):
                    fail(f"invalid SDK path parameter syntax: {service} {path}")
            endpoint_descriptors.add((service, method, path))
            endpoint_keys.add((service, wire_method(method), normalize_path(path)))

    if len(endpoint_descriptors) != sum(len(endpoints) for endpoints in inventory.values()):
        fail("contracts/sdk-endpoints.json contains duplicate service operations")

    client_source = (ROOT / "client.go").read_text(encoding="utf-8")
    for service in service_keys:
        field = "AI" if service == "ai" else "".join(part.title() for part in service.split("_"))
        binding = f'client.{field} = newService(core, "{service}")'
        if binding not in client_source:
            fail(f"SDK service {service!r} is missing its client namespace binding")

    generated = GENERATED_PATH.read_text(encoding="utf-8") if GENERATED_PATH.is_file() else ""
    if generated != generated_catalog(inventory):
        fail("pkg/resources/endpoints_generated.go is stale; run go generate ./pkg/resources")

    missing_operations = sorted(set(spec_operations) - endpoint_keys)
    if missing_operations:
        fail(f"OpenAPI operations have no SDK endpoint descriptor: {missing_operations}")

    print(
        f"validated {len(spec_operations)} OpenAPI operations, "
        f"{len(endpoint_descriptors)} SDK endpoint descriptors across {len(service_keys)} bound services, "
        "snapshot hashes, and generated catalog"
    )


if __name__ == "__main__":
    try:
        main()
    except (OSError, TypeError, KeyError) as error:
        print(f"contract validation failed: {error}", file=sys.stderr)
        raise SystemExit(1) from error
