#!/usr/bin/env python3
"""Generate Go endpoint descriptors from the committed SDK endpoint inventory."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "contracts/sdk-endpoints.json"
DESTINATION = ROOT / "models/endpoints_generated.go"

inventory = json.loads(SOURCE.read_text(encoding="utf-8"))
entries = []
for service in sorted(inventory):
    endpoints = inventory[service]
    for endpoint in sorted(endpoints, key=lambda item: (item["path"], item["method"])):
        entries.append(
            "\t{Service: %s, Method: %s, Path: %s},"
            % (
                json.dumps(service),
                json.dumps(endpoint["method"]),
                json.dumps(endpoint["path"]),
            )
        )

content = "// Code generated by scripts/generate_endpoints.py; DO NOT EDIT.\n\n"
content += "package models\n\n"
content += "var generatedEndpointCatalog = [...]Endpoint{\n"
content += "\n".join(entries)
content += "\n}\n"
DESTINATION.write_text(content, encoding="utf-8")
print(f"Wrote {len(entries)} endpoint descriptors to {DESTINATION.relative_to(ROOT)}")
