// Code generated by scripts/generate_services.py; DO NOT EDIT.

package agents

// Endpoint identifies a agents service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "GET", Path: "/agents"},
	{Method: "POST", Path: "/agents"},
	{Method: "GET", Path: "/agents/health"},
	{Method: "GET", Path: "/agents/runs/{param}"},
	{Method: "GET", Path: "/agents/runs/{param}/conversation"},
	{Method: "STREAM", Path: "/agents/runs/{param}/stream"},
	{Method: "DELETE", Path: "/agents/{param}"},
	{Method: "GET", Path: "/agents/{param}"},
	{Method: "PUT", Path: "/agents/{param}"},
	{Method: "POST", Path: "/agents/{param}/rollback"},
	{Method: "GET", Path: "/agents/{param}/runs"},
	{Method: "POST", Path: "/agents/{param}/runs"},
	{Method: "GET", Path: "/agents/{param}/versions"},
}
