// Code generated by scripts/generate_services.py; DO NOT EDIT.

package webhooks

// Endpoint identifies a webhooks service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "GET", Path: "/webhook-endpoints"},
	{Method: "POST", Path: "/webhook-endpoints"},
	{Method: "DELETE", Path: "/webhook-endpoints/{param}"},
	{Method: "GET", Path: "/webhook-endpoints/{param}"},
	{Method: "PATCH", Path: "/webhook-endpoints/{param}"},
	{Method: "GET", Path: "/webhook-endpoints/{param}/deliveries"},
	{Method: "POST", Path: "/webhook-endpoints/{param}/rotate-secret"},
	{Method: "GET", Path: "/webhooks"},
	{Method: "POST", Path: "/webhooks"},
	{Method: "GET", Path: "/webhooks/deliveries"},
	{Method: "GET", Path: "/webhooks/deliveries/{param}"},
	{Method: "POST", Path: "/webhooks/deliveries/{param}/retry"},
	{Method: "GET", Path: "/webhooks/stats"},
	{Method: "DELETE", Path: "/webhooks/{param}"},
	{Method: "GET", Path: "/webhooks/{param}"},
	{Method: "PUT", Path: "/webhooks/{param}"},
	{Method: "POST", Path: "/webhooks/{param}/rotate-secret"},
}
