// Code generated by scripts/generate_services.py; DO NOT EDIT.

package blob

// Endpoint identifies a blob service operation.
type Endpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

var generatedEndpoints = [...]Endpoint{
	{Method: "POST", Path: "/blob/object/copy"},
	{Method: "GET", Path: "/blob/object/info/{param}/{param}"},
	{Method: "POST", Path: "/blob/object/list/{param}"},
	{Method: "POST", Path: "/blob/object/move"},
	{Method: "POST", Path: "/blob/object/sign/{param}/{param}"},
	{Method: "DELETE", Path: "/blob/object/{param}/{param}"},
	{Method: "GET", Path: "/blob/object/{param}/{param}"},
	{Method: "POSTFORMDATA", Path: "/blob/object/{param}/{param}"},
}
